DROP TABLE IF EXISTS TRANSCRIPT;
CREATE TABLE TRANSCRIPT(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	video_id TEXT NOT NULL,
	url TEXT NOT NULL,
	language_code TEXT NOT NULL DEFAULT 'en',
	is_generated INTEGER NOT NULL DEFAULT 1
);

DROP TABLE IF EXISTS TRANSCRIPT_TEXT;
CREATE TABLE TRANSCRIPT_TEXT(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	video_id TEXT NOT NULL,
	text_data TEXT, 
	start real,
	duration real
);

DROP TABLE IF EXISTS TRANSCRIPT_FILE;
CREATE TABLE TRANSCRIPT_FILE(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	video_id TEXT NOT NULL,
	data BLOB 
);
